version: '3.5'
services:
  postgres:
    image: postgres:14-alpine
    container_name: postgres
    environment:
      POSTGRES_USER: 'admin'
      POSTGRES_PASSWORD: 'test'
      POSTGRES_DB: 'foxford-test'
    ports:
      - 5432:5432
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U admin -d foxford-test']
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    volumes:
      - ./db:/var/lib/postgresql/data
    networks:
      - postgres

networks:
  postgres:
    driver: bridge
